// General Types
export const SEND_EMAIL = 'SEND_EMAIL';
export const EMAIL_ERRORS = 'EMAIL_ERRORS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Types - Used in Registration and Login
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REG_SUCCESS = 'REG_SUCCESS';
export const DE_REGISTER = 'DE_REGISTER';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERRORS = 'AUTH_ERRORS';

// Company Profile Types
export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY_NAMES = 'GET_COMPANY_NAMES';
export const GET_ALL_COMPANY_TYPES = 'GET_ALL_COMPANY_TYPES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const SET_ADD_COMPANY_DIALOG = 'SET_ADD_COMPANY_DIALOG';
export const SET_EDIT_COMPANY_DIALOG = 'SET_EDIT_COMPANY_DIALOG';
export const SET_COMPANY_TO_EDIT = 'SET_COMPANY_TO_EDIT';
export const COMPANY_ERRORS = 'COMPANY_ERRORS';

// Team Members Types
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
export const GET_ALL_USER_TYPES = 'GET_ALL_USER_TYPES';
export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER';
export const DELETE_TEAM_MEMBER = 'DELETE_TEAM_MEMBER';
export const UPDATE_TEAM_MEMBER = 'UPDATE_TEAM_MEMBER';
export const SET_ADD_MEMBER_DIALOG = 'SET_ADD_MEMBER_DIALOG';
export const SET_EDIT_MEMBER_DIALOG = 'SET_EDIT_MEMBER_DIALOG';
export const SET_MEMBER_TO_EDIT = 'SET_MEMBER_TO_EDIT';
export const TEAM_ERRORS = 'TEAM_ERRORS';
export const MANAGE_TEAMLIST = 'MANAGE_TEAMLIST';

// Project Types
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_ALL_PROJECT_TYPES = 'GET_ALL_PROJECT_TYPES';
export const GET_PROJECT_NAMES = 'GET_PROJECT_NAMES';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const SET_ADD_PROJECT_DIALOG = 'SET_ADD_PROJECT_DIALOG';
export const SET_EDIT_PROJECT_DIALOG = 'SET_EDIT_PROJECT_DIALOG';
export const SET_PROJECT_TO_EDIT = 'SET_PROJECT_TO_EDIT';
export const PROJECT_ERRORS = 'PROJECT_ERRORS';
